//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.WP.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlineSatisEntities : DbContext
    {
        public onlineSatisEntities()
            : base("name=onlineSatisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<marka> marka { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
        public virtual DbSet<musteriAdres> musteriAdres { get; set; }
        public virtual DbSet<sepet> sepet { get; set; }
        public virtual DbSet<siparis> siparis { get; set; }
        public virtual DbSet<siparisDetay> siparisDetay { get; set; }
        public virtual DbSet<siparisDurum> siparisDurum { get; set; }
        public virtual DbSet<urun> urun { get; set; }
    }
}
