//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.WP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siparis()
        {
            this.siparisDetay = new HashSet<siparisDetay>();
        }
    
        public int siparisID { get; set; }
        public int musteriID { get; set; }
        public System.DateTime satisTarih { get; set; }
        public string toplamTutar { get; set; }
        public bool sepetteMi { get; set; }
        public string kargoTakipNo { get; set; }
        public int siparisDurumID { get; set; }
    
        public virtual musteri musteri { get; set; }
        public virtual siparisDurum siparisDurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparisDetay> siparisDetay { get; set; }
    }
}
