//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.WP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisDetay
    {
        public int siparisDetayID { get; set; }
        public int siparisID { get; set; }
        public int urunAdet { get; set; }
        public decimal toplamTutar { get; set; }
    
        public virtual siparis siparis { get; set; }
    }
}
