//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.WP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urun()
        {
            this.sepet = new HashSet<sepet>();
        }
    
        public int urunID { get; set; }
        public string urunAdi { get; set; }
        public decimal urunFiyati { get; set; }
        public System.DateTime urunEklenmeTarihi { get; set; }
        public int KategoriID { get; set; }
        public int MarkaID { get; set; }
        public string urunAciklama { get; set; }
        public int urunKDV { get; set; }
        public int urunStok { get; set; }
        public bool isActive { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual marka marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sepet> sepet { get; set; }
    }
}
